/** All user-facing copy lives here so Hindi/Marathi can be added. Use t(key). */
import { BRAND_NAME } from '@/lib/brand'
export type Lang = 'en' | 'hi' | 'mr'

const en = {
  home: 'Home',
  listings: 'Listings',
  leads: 'Leads',
  hello: 'Namaste',
  addListing: '+ Add listing',
  mySite: 'My website',
  open: 'Open',
  share: 'Share',
  shareWhatsapp: 'Share on WhatsApp',
  copyLink: 'Copy link',
  copied: 'Copied!',
  phoneLabel: 'Your mobile number',
  phonePlaceholder: '98765 43210',
  phoneInvalid: 'Enter a valid 10-digit Indian mobile number',
  sendOtp: 'Send OTP',
  otpLabel: 'Enter the 6-digit OTP',
  otpSentTo: 'OTP sent to',
  inviteLabel: 'Enter your 6-digit invite code',
  inviteFor: 'Invite code for',
  inviteHelp: 'Your personal code was sent to you on WhatsApp. No code yet? Message us and we will send one.',
  verify: 'Verify',
  resendIn: 'Resend OTP in',
  resend: 'Resend OTP',
  changeNumber: 'Change number',
  devHint: 'Dev only: OTP is',
  autofill: 'Fill it',
  yourName: 'Your name',
  yourCity: 'Your city',
  languages: 'Languages you speak',
  specialties: 'What do you sell?',
  createSite: 'Create my website',
  siteLive: 'Your website is live',
  addFirstListing: 'Add your first listing',
  goToStudio: 'Go to my app',
  loading: 'Please wait...',
  tryAgain: 'Try again',
  fixtureBanner: 'Demo mode: data is saved only on this phone',
  noListings: 'No listings yet. Add your first one!',
  noLeads: 'No leads yet. Share your listings to get enquiries.',
  hot: 'Hot',
  warm: 'Warm',
  cold: 'Cold',
  all: 'All',
  publish: 'Publish',
  markUnderOffer: 'Under offer',
  markSold: 'Mark sold',
  markRented: 'Mark rented',
  pause: 'Pause',
  makeLive: 'Make live',
  describe: 'Describe the property - e.g. 2 BHK in Baner, 85 lakh, ready possession',
  speak: 'Tap to speak',
  interest: 'Interest',
  newsroom: 'Newsroom',
  content: 'Content',
  agents: 'Agents',
  admin: 'Admin',
  profile: 'Profile',
  more: 'More',
  voicePremium: 'Voice listing',
  voicePremiumBadge: 'Premium',
  voicePremiumSub: 'Speak in Hindi, Marathi or English and we write the listing. Coming with Premium. For now, type the details.',
  stopRecording: 'Tap to stop',
  recording: 'Recording',
  micDenied: 'Microphone permission was denied. You can type instead.',
  micUnsupported: 'Voice recording is not supported on this phone. Please type.',
  reRecord: 'Record again',
  addPhotos: 'Add photos',
  takePhoto: 'Take photo',
  next: 'Next',
  needSomething: 'Type, speak or add photos first',
  reading: 'Reading your description...',
  review: 'Check and confirm',
  pleaseCheck: 'Please check',
  required: 'Required to publish',
  transcript: 'What we heard',
  warnings: 'Please note',
  confirmPost: 'Confirm & post',
  posting: 'Posting...',
  posted: 'Your listing is live',
  postAnother: 'Add another listing',
  back: 'Back',
  save: 'Save',
  call: 'Call',
  whatsapp: 'WhatsApp',
  addNote: 'Add a note',
  notePlaceholder: 'e.g. wants to visit Sunday',
  timeline: 'Activity',
  notes: 'Notes',
  logout: 'Log out',
  todayTitle: 'Your business today',
  tileNew: 'New enquiries',
  tileHot: 'Hot buyers',
  tileVisits: 'Site visits',
  tileFollowUps: 'Follow-ups due',
  hotBuyers: 'Hot buyers',
  followUpsDue: 'Follow-ups due',
  noHotBuyers: 'No hot buyers right now.',
  overdue: 'Overdue',
  dueToday: 'Due today',
  dueOn: 'Due',
  topMatch: 'Best match',
  newAgentTitle: 'Get your first enquiry',
  newAgentBody: 'Share your website and add a listing. Buyers who enquire will show up here, with what they want.',
  shareSite: 'Share your website',
  filterShowing: 'Showing',
  clearFilter: 'Show all',
  aiSummary: 'AI summary',
  nextStep: 'Best next step',
  actCall: 'Call now',
  actWhatsapp: 'Message on WhatsApp',
  actScheduleVisit: 'Schedule a site visit',
  actFollowUp: 'Follow up',
  whatTheyWant: 'What they want',
  reqStated: 'Stated by the buyer',
  reqInferred: 'Read from their message',
  reqMixed: 'Partly stated, partly read from their message',
  noRequirement: 'They have not shared what they want yet.',
  timelineNow: 'Buying now',
  timeline1_3: 'In 1-3 months',
  timeline3_6: 'In 3-6 months',
  timelineExploring: 'Just looking',
  finHomeLoan: 'Home loan',
  finOwnFunds: 'Own funds',
  finUndecided: 'Payment not sure',
  matchingProperties: 'Matching properties',
  noMatches: 'No matching listings yet.',
  matchPct: 'match',
  followUpDue: 'Follow-up',
  followUpNone: 'No follow-up set',
  followUpOverdue: 'Follow-up overdue since',
  followUpOn: 'Follow up on',
  fuTomorrow: 'Tomorrow',
  fu3Days: 'In 3 days',
  fuNextWeek: 'Next week',
  draftFollowUp: 'Draft follow-up',
  drafting: 'Writing your message...',
  yourMessage: 'Your message',
  whySection: 'Why this message',
  sendOnWhatsapp: 'Send on WhatsApp',
  neverSends: 'We never send anything for you. You read it, edit it, and tap send.',
  langEn: 'EN',
  langHi: 'HI',
  langMr: 'MR',
  langFallback: 'This language is not ready yet, so the message is in English.',
  stage: 'Stage',
  notFound: 'Not found',
  propertyReady: 'Your property is ready',
  propertyReadySub: 'It is live on your website. Now share it.',
  creatingMarketing: 'Creating your marketing...',
  marketingTitle: 'Marketing',
  startMarketing: 'Start marketing',
  postsLanguage: 'Posts in',
  langEnglish: 'English',
  langMarathi: 'मराठी',
  langHindi: 'हिंदी',
  startMarketingHelp: 'First we check the project facts and add them to your listing page. Then we make your posts from those facts.',
  stepFacts: 'Project facts and listing page',
  stepPosts: 'Posts from those facts',
  stepWaiting: 'Waiting',
  stepWorking: 'Working...',
  stepDone: 'Done',
  factsFound: 'facts checked',
  nearbyFound: 'nearby places',
  onMaharera: 'MahaRERA',
  viewPage: 'See the listing page',
  postsReady: 'posts ready for your approval',
  postReady: 'post ready for your approval',
  makeAgain: 'Check again and remake',
  sendToCalendar: 'Send to calendar for approval',
  reelsTitle: 'Reels',
  editCaption: 'Caption',
  saveCaption: 'Save caption',
  saved: 'Saved',
  checkWarnings: 'Saved. Please check:',
  improveNote: 'What should change?',
  improveNotePlaceholder: 'e.g. mention it is near MIDC',
  improve: 'Make it again with this note',
  improving: 'Making it again...',
  editedTag: 'edited',
  walkthroughReel: 'Walkthrough reel',
  walkthroughMaking: 'being made; send to the calendar again once it is ready',
  walkthroughSkipped: 'not made',
  sentToCalendar: 'planned in the calendar, one a day from',
  approveInCalendar: 'Approve them in Content',
  runFailed: 'Something went wrong.',
  marketingFailed: 'We could not create your marketing right now. Your property is already live.',
  packLanguage: 'Language',
  packLangFallback: 'This language is not ready yet, so your marketing is in English.',
  instagram: 'Instagram',
  facebook: 'Facebook',
  reel: 'Reel script',
  copyCaption: 'Copy caption',
  copyPost: 'Copy post',
  copyMessage: 'Copy message',
  copyScript: 'Copy script',
  downloadImage: 'Download image',
  downloadStatusImage: 'Download status image',
  shareImage: 'Share',
  whatsappStatus: 'WhatsApp status',
  reelHook: 'Hook',
  reelCta: 'Call to action',
  publishEverywhere: 'Publish everywhere',
  publishNote: 'Later you will be able to connect your own Instagram, Facebook and WhatsApp Business accounts and post from them. For now you copy or share each item yourself.',
  socialTitle: `Post to ${BRAND_NAME}`,
  socialExplain: `We can post this on the ${BRAND_NAME} Facebook Page and Instagram. Posts go out as the ${BRAND_NAME} team, with no name or phone number: buyers tap Interested or comment, and you follow up from your inbox.`,
  socialTestBanner: 'Test mode: nothing is posted publicly.',
  socialFacebookPage: 'Facebook Page',
  socialInstagram: 'Instagram',
  socialNotSetUp: 'Not set up yet',
  socialConsent: `I agree to post this listing, on the ${BRAND_NAME} Page.`,
  socialApprove: 'Approve and post',
  socialApproveTest: 'Approve and test post',
  socialPosting: 'Posting...',
  socialPosted: 'Posted',
  socialTestPost: 'Test post',
  socialFailed: 'Failed',
  socialQueued: 'Queued',
  socialDone: 'Done',
  socialPostAgain: 'Post again',
  socialViewPost: 'View post',
  socialResults: 'Results',
  socialHistory: 'Earlier posts',
  socialHistoryEmpty: 'Nothing has been posted for this listing yet.',
  socialVersion: 'Version',
  socialLoadFailed: 'We could not load the posting options right now. You can still copy and share below.',
  socialNotReady: 'This listing cannot be posted yet. Make sure it is live and your marketing is ready, then try again.',
  socialAlreadyPosted: 'This was already posted. Tap Post again if you want to post it once more.',
  socialErrNotConfigured: 'This channel is not set up yet. Please tell support.',
  socialErrAccount: `The ${BRAND_NAME} account needs to be reconnected. Please tell support.`,
  socialErrImage: 'The photo could not be used. Try again in a few minutes.',
  socialErrGeneric: 'The post did not go through. Please try again in a few minutes.',
  socialDetails: 'Details',
  connectInstagram: 'Connect Instagram',
  connectFacebook: 'Connect Facebook',
  connectWhatsappBusiness: 'Connect WhatsApp Business',
  comingSoon: 'Coming soon',
  buyersMatchOne: 'of your buyers match this property',
  noBuyersMatch: 'None of your buyers match this property yet. When new buyers enquire, they will show up here.',
  neverSendsShort: 'We never send anything for you.',
  editMessage: 'Edit message',
  hideMessage: 'Hide message',
  buyersLoadFailed: 'Could not load matching buyers.',
  aiRecommends: 'AI recommends',
  actSendProperty: 'Send property',
  actCreateMarketing: 'Create marketing',
  marketing: 'Marketing',
  buyersWhoMatch: 'Buyers who match',
  perfViews: 'views',
  perfEnquiries: 'enquiries',
  perfQualified: 'qualified',
  perfVisits: 'site visits',
  perfDeal: 'deal',
  perfDeals: 'deals',
  dealClosedTitle: 'Deal closed',
  dealClosedSub: 'Congratulations! Add the details if you have them. Both are optional.',
  dealPrice: 'Deal price',
  dealPriceHelp: 'e.g. 85 lakh or 1.2 crore. You can change it.',
  dealPriceInvalid: 'Enter an amount like 85 lakh, 1.2 crore or 8500000.',
  dealProperty: 'Which property?',
  dealNoProperty: 'Not sure / other property',
  saveDeal: 'Save',
  lostTitle: 'Why was it lost?',
  lostSub: 'Tap a reason. It helps you see what to fix.',
  skip: 'Skip',
  close: 'Close',
  reasonPrice: 'Price',
  reasonBoughtElsewhere: 'Bought elsewhere',
  reasonNotResponding: 'Not responding',
  reasonChangedMind: 'Changed mind',
  reasonOther: 'Other',
  reasonPriceShort: 'price',
  reasonBoughtElsewhereShort: 'bought elsewhere',
  reasonNotRespondingShort: 'not responding',
  reasonChangedMindShort: 'changed mind',
  reasonOtherShort: 'other reason',
  outcomeWon: 'Won',
  outcomeLost: 'Lost',
  outcomeOnThe: 'on the',
  reopen: 'Reopen',
  reopenHint: 'Moves this buyer back to Contacted.',
  markListingSoldQ: 'Mark',
  markListingAsSold: 'as sold?',
  markListingAsRented: 'as rented?',
  thisProperty: 'this property',
  markSuggestSub: 'This keeps your listings up to date.',
  yes: 'Yes',
  notNow: 'Not now',
  thisMonth: 'This month',
  dealsWon: 'Deals won',
  dealValue: 'Deal value',
  bestChannel: 'Best channel',
  mostLost: 'Most lost on',
  lostOne: 'deal lost this month',
  lostMany: 'deals lost this month',
  activity: 'Activity',
  activityTitle: 'Activity',
  activityLoadFailed: 'We could not load the activity right now.',
  actViews: 'Views',
  actVisitors: 'Visitors',
  actEnquiries: 'Enquiries',
  actQualified: 'Qualified',
  actSiteVisits: 'Site visits',
  actDeals: 'Deals',
  actWhatsappTaps: 'WhatsApp taps',
  actCalls: 'Calls',
  actShares: 'Shares',
  actLast14: 'Last 14 days',
  actChartViews: 'Views',
  actChartEnquiries: 'Enquiries',
  actChartNone: 'No views in the last 14 days.',
  actSources: 'Where they came from',
  actSourcesEmpty: 'We will show where your buyers come from once people open this listing.',
  actSourceView: 'view',
  actSourceViews: 'views',
  actSourceEnquiry: 'enquiry',
  actSourceEnquiries: 'enquiries',
  actPeople: 'Interested people',
  actPeopleEmpty: 'Nobody has enquired about this listing yet.',
  actRecent: 'Recent activity',
  actRecentEmpty: 'Nothing has happened on this listing yet.',
  actEmptyTitle: 'No views yet',
  actEmptyBody: 'Share this listing on WhatsApp and in your groups. Every view and enquiry will show up here.',
  actOpenLead: 'Open',
  actLead: 'Buyer',
  actVisitor: 'Visitor',
  actYesterday: 'Yesterday',
  freshAskTitle: 'Is this still available?',
  freshAskBody: 'Buyers only see listings that are still available.',
  freshHiddenTitle: 'Hidden from buyers until you confirm',
  freshHiddenBody: 'Buyers cannot see this listing right now. Confirm it to show it again.',
  freshConfirmedDays: 'Last confirmed',
  freshDaysAgo: 'days ago',
  freshYes: 'Yes, still available',
  freshSold: 'It is sold',
  freshRented: 'It is rented',
  freshPause: 'Pause it',
  freshConfirmChip: 'Confirm',
  freshHiddenChip: 'Hidden',
  freshThanks: 'Thanks. Buyers can see it.',
  freshSoldDone: 'Marked as sold.',
  freshRentedDone: 'Marked as rented.',
  freshPausedDone: 'Paused. Buyers cannot see it.',
  freshSectionLabel: 'Listings to confirm',
  actConfirmListing: 'Confirm now',
  actConfirmTitle: 'Listings that need your confirmation',
  actConfirmOne: 'listing needs a quick check',
  actConfirmMany: 'listings need a quick check',
  actConfirmHidden: 'hidden from buyers until you confirm',
  aboutTitle: 'About the project and area',
  aboutHelp: 'This is what lets your assistant answer the questions buyers ask, on your behalf. Tap what is true. Skip anything you are not sure about.',
  aboutSuggest: 'Suggest from my description and the area guide',
  aboutSuggesting: 'Reading your description...',
  aboutSuggestNone: 'Nothing new to suggest. Add details by tapping the chips below.',
  aboutSuggestHint: 'Suggestions are drafts: keep only what is true.',
  aboutFromYou: 'You said',
  aboutFromGuide: 'Area guide',
  aboutKeep: 'Keep',
  aboutRemove: 'Remove',
  aboutKeepAll: 'Keep all',
  aboutAmenities: 'Amenities',
  aboutNearby: 'Nearby',
  aboutHighlights: 'Highlights',
  aboutHighlightAdd: 'Add a highlight (max 6)',
  aboutConnectivity: 'Roads and connectivity',
  aboutProject: 'Project or society name',
  aboutWater: 'Water',
  aboutPower: 'Power backup',
  aboutMaintenance: 'Maintenance',
  aboutParking: 'Parking',
  aboutSociety: 'Society',
  aboutFaqTitle: 'Questions buyers ask: add your answer',
  aboutFaqAnswer: 'Your answer',
  aboutContinue: 'Continue',
  aboutSkip: 'Skip for now',
  aboutSummaryTitle: 'About the project and area',
  aboutSummaryEmpty: 'Not added. Adding it helps your assistant answer buyers.',
  aboutEdit: 'Edit',
  aboutAdd: 'Add',
  aboutPublicNearby: 'Nearby',
  aboutPublicAbout: 'About the project',
  aboutPublicGetting: 'Getting around',
  aboutPublicHighlights: 'Highlights',
  aboutPublicAmenities: 'Amenities',
  aboutNoContact: 'Please do not type phone numbers or links here.',
} as const

export type StringKey = keyof typeof en

const hi: Partial<Record<StringKey, string>> = {
  home: 'होम',
  listings: 'लिस्टिंग',
  leads: 'ग्राहक',
  hello: 'नमस्ते',
  addListing: '+ लिस्टिंग जोड़ें',
  shareWhatsapp: 'WhatsApp पर शेयर करें',
  sendOtp: 'OTP भेजें',
  verify: 'जाँचें',
  aboutTitle: 'प्रोजेक्ट और इलाके की जानकारी',
  aboutHelp: 'इसी से आपका असिस्टेंट खरीदारों के सवालों के जवाब दे पाता है। जो सही है उसे चुनें। जिसके बारे में पक्का नहीं, छोड़ दें।',
  aboutSuggest: 'मेरे विवरण और इलाके की गाइड से सुझाव लें',
  aboutFromYou: 'आपने कहा',
  aboutFromGuide: 'इलाके की गाइड',
  aboutKeep: 'रखें',
  aboutRemove: 'हटाएं',
  aboutAmenities: 'सुविधाएं',
  aboutNearby: 'आसपास',
  aboutWater: 'पानी',
  aboutPower: 'पावर बैकअप',
  aboutMaintenance: 'मेंटेनेंस',
  aboutParking: 'पार्किंग',
  aboutSociety: 'सोसाइटी',
  aboutFaqTitle: 'खरीदार जो पूछते हैं: अपना जवाब जोड़ें',
  aboutContinue: 'आगे बढ़ें',
  aboutSkip: 'अभी छोड़ें',
  aboutPublicNearby: 'आसपास',
  aboutPublicAbout: 'प्रोजेक्ट के बारे में',
  aboutPublicHighlights: 'खास बातें',
  aboutPublicAmenities: 'सुविधाएं',
}

const mr: Partial<Record<StringKey, string>> = {
  aboutTitle: 'प्रकल्प आणि परिसराची माहिती',
  aboutHelp: 'यामुळेच तुमचा असिस्टंट खरेदीदारांच्या प्रश्नांची उत्तरे देऊ शकतो. जे खरे आहे ते निवडा. खात्री नसेल ते सोडा.',
  aboutSuggest: 'माझ्या वर्णनावरून आणि परिसर मार्गदर्शकावरून सुचवा',
  aboutFromYou: 'तुम्ही सांगितले',
  aboutFromGuide: 'परिसर मार्गदर्शक',
  aboutKeep: 'ठेवा',
  aboutRemove: 'काढा',
  aboutAmenities: 'सुविधा',
  aboutNearby: 'जवळपास',
  aboutWater: 'पाणी',
  aboutPower: 'पॉवर बॅकअप',
  aboutMaintenance: 'देखभाल शुल्क',
  aboutParking: 'पार्किंग',
  aboutSociety: 'सोसायटी',
  aboutFaqTitle: 'खरेदीदार विचारतात: तुमचे उत्तर जोडा',
  aboutContinue: 'पुढे',
  aboutSkip: 'आत्ता वगळा',
  aboutPublicNearby: 'जवळपास',
  aboutPublicAbout: 'प्रकल्पाबद्दल',
  aboutPublicHighlights: 'वैशिष्ट्ये',
  aboutPublicAmenities: 'सुविधा',
}

const tables: Record<Lang, Partial<Record<StringKey, string>>> = { en, hi, mr }
let current: Lang = 'en'

export function setLang(l: Lang) {
  current = l
}

export function t(key: StringKey): string {
  return tables[current][key] ?? en[key]
}
