/** All user-facing copy lives here so Hindi/Marathi can be added. Use t(key). */
export type Lang = 'en' | 'hi' | 'mr'

const en = {
  home: 'Home',
  listings: 'Listings',
  leads: 'Leads',
  hello: 'Namaste',
  addListing: '+ Add listing',
  mySite: 'My website',
  open: 'Open',
  share: 'Share',
  shareWhatsapp: 'Share on WhatsApp',
  copyLink: 'Copy link',
  copied: 'Copied!',
  phoneLabel: 'Your mobile number',
  phonePlaceholder: '98765 43210',
  phoneInvalid: 'Enter a valid 10-digit Indian mobile number',
  sendOtp: 'Send OTP',
  otpLabel: 'Enter the 6-digit OTP',
  otpSentTo: 'OTP sent to',
  inviteLabel: 'Enter your 6-digit invite code',
  inviteFor: 'Invite code for',
  inviteHelp: 'Your personal code was sent to you on WhatsApp. No code yet? Message us and we will send one.',
  verify: 'Verify',
  resendIn: 'Resend OTP in',
  resend: 'Resend OTP',
  changeNumber: 'Change number',
  devHint: 'Dev only: OTP is',
  autofill: 'Fill it',
  yourName: 'Your name',
  yourCity: 'Your city',
  languages: 'Languages you speak',
  specialties: 'What do you sell?',
  createSite: 'Create my website',
  siteLive: 'Your website is live',
  addFirstListing: 'Add your first listing',
  goToStudio: 'Go to my app',
  loading: 'Please wait...',
  tryAgain: 'Try again',
  fixtureBanner: 'Demo mode: data is saved only on this phone',
  noListings: 'No listings yet. Add your first one!',
  noLeads: 'No leads yet. Share your listings to get enquiries.',
  hot: 'Hot',
  warm: 'Warm',
  cold: 'Cold',
  all: 'All',
  publish: 'Publish',
  markUnderOffer: 'Under offer',
  markSold: 'Mark sold',
  markRented: 'Mark rented',
  pause: 'Pause',
  makeLive: 'Make live',
  describe: 'Describe the property - e.g. 2 BHK in Baner, 85 lakh, ready possession',
  speak: 'Tap to speak',
  stopRecording: 'Tap to stop',
  recording: 'Recording',
  micDenied: 'Microphone permission was denied. You can type instead.',
  micUnsupported: 'Voice recording is not supported on this phone. Please type.',
  reRecord: 'Record again',
  addPhotos: 'Add photos',
  takePhoto: 'Take photo',
  next: 'Next',
  needSomething: 'Type, speak or add photos first',
  reading: 'Reading your description...',
  review: 'Check and confirm',
  pleaseCheck: 'Please check',
  required: 'Required to publish',
  transcript: 'What we heard',
  warnings: 'Please note',
  confirmPost: 'Confirm & post',
  posting: 'Posting...',
  posted: 'Your listing is live',
  postAnother: 'Add another listing',
  back: 'Back',
  save: 'Save',
  call: 'Call',
  whatsapp: 'WhatsApp',
  addNote: 'Add a note',
  notePlaceholder: 'e.g. wants to visit Sunday',
  timeline: 'Activity',
  notes: 'Notes',
  logout: 'Log out',
  todayTitle: 'Your business today',
  tileNew: 'New enquiries',
  tileHot: 'Hot buyers',
  tileVisits: 'Site visits',
  tileFollowUps: 'Follow-ups due',
  hotBuyers: 'Hot buyers',
  followUpsDue: 'Follow-ups due',
  noHotBuyers: 'No hot buyers right now.',
  overdue: 'Overdue',
  dueToday: 'Due today',
  dueOn: 'Due',
  topMatch: 'Best match',
  newAgentTitle: 'Get your first enquiry',
  newAgentBody: 'Share your website and add a listing. Buyers who enquire will show up here, with what they want.',
  shareSite: 'Share your website',
  filterShowing: 'Showing',
  clearFilter: 'Show all',
  aiSummary: 'AI summary',
  nextStep: 'Best next step',
  actCall: 'Call now',
  actWhatsapp: 'Message on WhatsApp',
  actScheduleVisit: 'Schedule a site visit',
  actFollowUp: 'Follow up',
  whatTheyWant: 'What they want',
  reqStated: 'Stated by the buyer',
  reqInferred: 'Read from their message',
  reqMixed: 'Partly stated, partly read from their message',
  noRequirement: 'They have not shared what they want yet.',
  timelineNow: 'Buying now',
  timeline1_3: 'In 1-3 months',
  timeline3_6: 'In 3-6 months',
  timelineExploring: 'Just looking',
  finHomeLoan: 'Home loan',
  finOwnFunds: 'Own funds',
  finUndecided: 'Payment not sure',
  matchingProperties: 'Matching properties',
  noMatches: 'No matching listings yet.',
  matchPct: 'match',
  followUpDue: 'Follow-up',
  followUpNone: 'No follow-up set',
  followUpOverdue: 'Follow-up overdue since',
  followUpOn: 'Follow up on',
  fuTomorrow: 'Tomorrow',
  fu3Days: 'In 3 days',
  fuNextWeek: 'Next week',
  draftFollowUp: 'Draft follow-up',
  drafting: 'Writing your message...',
  yourMessage: 'Your message',
  whySection: 'Why this message',
  sendOnWhatsapp: 'Send on WhatsApp',
  neverSends: 'We never send anything for you. You read it, edit it, and tap send.',
  langEn: 'EN',
  langHi: 'HI',
  langMr: 'MR',
  langFallback: 'This language is not ready yet, so the message is in English.',
  stage: 'Stage',
  notFound: 'Not found',
  propertyReady: 'Your property is ready',
  propertyReadySub: 'It is live on your website. Now share it.',
  creatingMarketing: 'Creating your marketing...',
  marketingTitle: 'Marketing',
  marketingFailed: 'We could not create your marketing right now. Your property is already live.',
  packLanguage: 'Language',
  packLangFallback: 'This language is not ready yet, so your marketing is in English.',
  instagram: 'Instagram',
  facebook: 'Facebook',
  reel: 'Reel script',
  copyCaption: 'Copy caption',
  copyPost: 'Copy post',
  copyMessage: 'Copy message',
  copyScript: 'Copy script',
  downloadImage: 'Download image',
  downloadStatusImage: 'Download status image',
  shareImage: 'Share',
  whatsappStatus: 'WhatsApp status',
  reelHook: 'Hook',
  reelCta: 'Call to action',
  publishEverywhere: 'Publish everywhere',
  publishNote: 'For now you copy or share each item yourself. Connecting your accounts is coming soon.',
  connectInstagram: 'Connect Instagram',
  connectFacebook: 'Connect Facebook',
  connectWhatsappBusiness: 'Connect WhatsApp Business',
  comingSoon: 'Coming soon',
  buyersMatchOne: 'of your buyers match this property',
  noBuyersMatch: 'None of your buyers match this property yet. When new buyers enquire, they will show up here.',
  neverSendsShort: 'We never send anything for you.',
  editMessage: 'Edit message',
  hideMessage: 'Hide message',
  buyersLoadFailed: 'Could not load matching buyers.',
  aiRecommends: 'AI recommends',
  actSendProperty: 'Send property',
  actCreateMarketing: 'Create marketing',
  marketing: 'Marketing',
  buyersWhoMatch: 'Buyers who match',
  perfViews: 'views',
  perfEnquiries: 'enquiries',
  perfQualified: 'qualified',
  perfVisits: 'site visits',
} as const

export type StringKey = keyof typeof en

const hi: Partial<Record<StringKey, string>> = {
  home: 'होम',
  listings: 'लिस्टिंग',
  leads: 'ग्राहक',
  hello: 'नमस्ते',
  addListing: '+ लिस्टिंग जोड़ें',
  shareWhatsapp: 'WhatsApp पर शेयर करें',
  sendOtp: 'OTP भेजें',
  verify: 'जाँचें',
}

const tables: Record<Lang, Partial<Record<StringKey, string>>> = { en, hi, mr: {} }
let current: Lang = 'en'

export function setLang(l: Lang) {
  current = l
}

export function t(key: StringKey): string {
  return tables[current][key] ?? en[key]
}
