labels:
  - name: epic
    color: 8b00ff
    description: High-level initiative
  - name: feature
    color: 00aaff
    description: New user-facing capability
  - name: bug
    color: d73a4a
    description: Something isn’t working
  - name: tech-debt
    color: 6e7781
    description: Cleanup, refactor, infra
  - name: priority:high
    color: b60205
  - name: priority:medium
    color: d4c5f9
  - name: priority:low
    color: cccccc
  - name: area:fb
    color: 1877f2
  - name: area:auth
    color: 5319e7
  - name: area:data
    color: 0e8a16
  - name: area:ai
    color: 0366d6
  - name: area:ui
    color: fbca04
  - name: area:ops
    color: 0052cc

milestones:
  - title: Week 1
    description: Stabilize Mongo-only + Facebook endpoints; auth hardening; tests
  - title: Week 2
    description: FB happy-path demo (mocked), reminders, CI artifacts
  - title: Weeks 3-4
    description: RBAC, audit trail, analytics MVP, observability

issues:
  # Epic 1: Mongo-only migration + Facebook stabilization
  - title: "Epic: Complete Mongo-only migration and stabilize Facebook integration"
    body: |
      Track and deliver end-to-end migration from SQLite to Mongo and stabilize Facebook endpoints.

      See docs/product_discovery_and_roadmap.md (Epic 1).
    labels: [epic, priority:high, area:data, area:fb]
    milestone: Week 1

  - title: Remove all residual SQLite references and code paths
    body: |
      Sweep repository and remove any SQLite branches, helpers, or migrations. Ensure Mongo-only.
      - Verify no .db usage
      - Verify adapter paths
      - Update docs
    labels: [tech-debt, area:data, priority:high]
    milestone: Week 1

  - title: Fix 500s on /api/facebook/config and /api/facebook/pages
    body: |
      Ensure endpoints return stable responses when not connected and work with Mongo user state.
      - Handle first-time users (no fb tokens)
      - JWT payload alignment
      - Add error guards and logs
      - Update tests to expect 200/400 appropriately
    labels: [bug, area:fb, priority:high]
    milestone: Week 1

  - title: Add Facebook integration tests with mocks (config/pages/select/post)
    body: |
      Mock Graph API responses; cover happy-path and error states without external calls.
      - Feature flag external calls
      - Unit + integration levels
    labels: [feature, area:fb, priority:high]
    milestone: Week 1

  - title: Stabilize JWT issuance/verification and add smoke tests
    body: |
      Use python-jose consistently; ensure exp validation and friendly errors.
      - Add smoke tests for token expiry/invalid signatures
    labels: [tech-debt, area:auth, priority:high]
    milestone: Week 1

  - title: Add /health endpoint for probes
    body: |
      Provide a lightweight health check returning 200 {status: "ok"} for readiness/liveness.
    labels: [feature, area:ops, priority:medium]
    milestone: Week 1

  # Epic 2: Agent productivity
  - title: "Epic: Agent productivity (scoring, reminders, templates)"
    body: |
      Improve agent velocity: smart lead scoring, reminders/follow-ups, tagging and templates.
      See docs/product_discovery_and_roadmap.md (Epic 2).
    labels: [epic, area:ui]
    milestone: Week 2

  - title: Smart lead scoring MVP
    body: |
      Simple heuristic (rules-based) scoring; show on dashboard and lists.
      Acceptance: score appears; configurable weights.
    labels: [feature, area:ai, priority:medium]
    milestone: Week 2

  - title: Follow-up reminders and simple queue
    body: |
      Allow scheduling and viewing upcoming follow-ups; basic notifications in UI.
    labels: [feature, area:ui, priority:high]
    milestone: Week 2

  - title: Tagging/segments and saved filters
    body: |
      Add tags to leads/properties; saved filters on lists.
    labels: [feature, area:ui]
    milestone: Week 2

  - title: Templates for email/WhatsApp with quick replies
    body: |
      Library of reusable message templates; quick insert in UI.
    labels: [feature, area:ui]
    milestone: Week 2

  # Epic 3: Marketing/social
  - title: "Epic: Marketing & social suite"
    body: |
      FB posting history, Instagram via FB Graph, WhatsApp helpers, UTM tracking.
      See docs/product_discovery_and_roadmap.md (Epic 3).
    labels: [epic, area:fb]
    milestone: Weeks 3-4

  - title: Facebook posting history and status in UI
    body: |
      Display recent posts and connection status; retries for failures.
    labels: [feature, area:fb]
    milestone: Weeks 3-4

  - title: Instagram integration via FB Graph (basic)
    body: |
      Support simple cross-post to Instagram accounts connected to FB pages.
    labels: [feature, area:fb]
    milestone: Weeks 3-4

  - title: WhatsApp Business deep-link helpers
    body: |
      Provide deep-link helpers and prefilled templates; no server-side integration yet.
    labels: [feature, area:ui]
    milestone: Weeks 3-4

  - title: UTM tracking and campaign reporting MVP
    body: |
      Track campaign params for inbound leads and post links.
    labels: [feature, area:ops]
    milestone: Weeks 3-4

  # Epic 4: Collaboration & permissions
  - title: "Epic: RBAC and audit trail"
    body: |
      Roles (Agent/Manager/Admin), sharing, approvals, and basic audit log.
    labels: [epic, area:ops]
    milestone: Weeks 3-4

  - title: Implement RBAC roles and permissions checks
    body: |
      Add roles to users; enforce on endpoints and UI sections.
    labels: [feature, area:ops]
    milestone: Weeks 3-4

  - title: Activity log / audit trail (append-only)
    body: |
      Record key actions (CRUD, auth events) with timestamps and actor.
    labels: [feature, area:ops]
    milestone: Weeks 3-4

  # Epic 5: Analytics & dashboards
  - title: "Epic: Analytics & dashboards"
    body: |
      Team dashboards, funnel metrics, property performance.
    labels: [epic, area:ui]
    milestone: Weeks 3-4

  - title: Per-agent dashboard cards (leads, conversions)
    body: |
      Add KPIs and trends per agent; export CSV.
    labels: [feature, area:ui]
    milestone: Weeks 3-4

  - title: Property performance metrics
    body: |
      Views, inquiries; correlate with posting activity.
    labels: [feature, area:ui]
    milestone: Weeks 3-4

  # Epic 6: Reliability & ops
  - title: "Epic: Reliability & ops hardening"
    body: |
      Structured logs, metrics, rate limiting, security headers, backups/DR.
    labels: [epic, area:ops]
    milestone: Weeks 3-4

  - title: Structured logging and minimal metrics
    body: |
      Adopt structured JSON logs; expose basic metrics endpoints.
    labels: [tech-debt, area:ops]
    milestone: Weeks 3-4

  - title: Rate limiting, validation hardening, security headers
    body: |
      Basic protections for public endpoints; align with best practices.
    labels: [tech-debt, area:ops]
    milestone: Weeks 3-4

  - title: Backups and disaster recovery playbooks
    body: |
      Define and test backup/restore; document procedures.
    labels: [tech-debt, area:ops]
    milestone: Weeks 3-4
