/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Design System Colors - Integrated with CSS Custom Properties
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        tertiary: {
          50: 'var(--color-tertiary-50)',
          100: 'var(--color-tertiary-100)',
          200: 'var(--color-tertiary-200)',
          300: 'var(--color-tertiary-300)',
          400: 'var(--color-tertiary-400)',
          500: 'var(--color-tertiary-500)',
          600: 'var(--color-tertiary-600)',
          700: 'var(--color-tertiary-700)',
          800: 'var(--color-tertiary-800)',
          900: 'var(--color-tertiary-900)',
          950: 'var(--color-tertiary-950)',
        },
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
        },
        // Semantic colors
        surface: 'var(--color-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-inverse-secondary': 'var(--color-text-inverse-secondary)',
        'text-inverse-tertiary': 'var(--color-text-inverse-tertiary)',
        border: 'var(--color-border)',
        'border-variant': 'var(--color-border-variant)',
        'border-focus': 'var(--color-border-focus)',
        'border-error': 'var(--color-border-error)',
        'border-success': 'var(--color-border-success)',
        'border-warning': 'var(--color-border-warning)',
      },
      fontFamily: {
        sans: ['var(--font-family-primary)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-family-mono)', 'monospace'],
        display: ['var(--font-family-display)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Design System Typography Scale
        'display-large': ['var(--text-display-large)', { lineHeight: 'var(--line-height-display)' }],
        'display-medium': ['var(--text-display-medium)', { lineHeight: 'var(--line-height-display)' }],
        'display-small': ['var(--text-display-small)', { lineHeight: 'var(--line-height-display)' }],
        'headline-large': ['var(--text-headline-large)', { lineHeight: 'var(--line-height-headline)' }],
        'headline-medium': ['var(--text-headline-medium)', { lineHeight: 'var(--line-height-headline)' }],
        'headline-small': ['var(--text-headline-small)', { lineHeight: 'var(--line-height-headline)' }],
        'title-large': ['var(--text-title-large)', { lineHeight: 'var(--line-height-title)' }],
        'title-medium': ['var(--text-title-medium)', { lineHeight: 'var(--line-height-title)' }],
        'title-small': ['var(--text-title-small)', { lineHeight: 'var(--line-height-title)' }],
        'label-large': ['var(--text-label-large)', { lineHeight: 'var(--line-height-label)' }],
        'label-medium': ['var(--text-label-medium)', { lineHeight: 'var(--line-height-label)' }],
        'label-small': ['var(--text-label-small)', { lineHeight: 'var(--line-height-label)' }],
        'body-large': ['var(--text-body-large)', { lineHeight: 'var(--line-height-body)' }],
        'body-medium': ['var(--text-body-medium)', { lineHeight: 'var(--line-height-body)' }],
        'body-small': ['var(--text-body-small)', { lineHeight: 'var(--line-height-body)' }],
      },
      spacing: {
        // Design System Spacing Scale (8px grid)
        '0-5': 'var(--space-0-5)',
        '1-5': 'var(--space-1-5)',
        '2-5': 'var(--space-2-5)',
        '3-5': 'var(--space-3-5)',
        '7': 'var(--space-7)',
        '9': 'var(--space-9)',
        '11': 'var(--space-11)',
        '14': 'var(--space-14)',
        '18': 'var(--space-18)',
        '28': 'var(--space-28)',
        '36': 'var(--space-36)',
        '44': 'var(--space-44)',
        '52': 'var(--space-52)',
        '60': 'var(--space-60)',
        '72': 'var(--space-72)',
        '80': 'var(--space-80)',
        '96': 'var(--space-96)',
      },
      boxShadow: {
        // Design System Shadows
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'var(--shadow-inner)',
        // Legacy shadows for backward compatibility
        '3xl': '0 35px 60px -12px rgba(0, 0, 0, 0.25)',
        'focus': '0 0 0 3px rgba(59, 130, 246, 0.5)',
        'focus-inset': 'inset 0 0 0 3px rgba(59, 130, 246, 0.5)',
        'focus-accessible': '0 0 0 2px rgba(59, 130, 246, 0.8)',
        'focus-error': '0 0 0 2px rgba(239, 68, 68, 0.8)',
        'focus-success': '0 0 0 2px rgba(34, 197, 94, 0.8)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-2px)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      minHeight: {
        'touch-target': '44px', // Minimum touch target size
      },
      minWidth: {
        'touch-target': '44px', // Minimum touch target size
      },
    },
  },
  plugins: [],
}
