version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crm_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: real_estate_crm
    volumes:
      - mongodb_data:/data/db
    networks:
      - crm_network

  app:
    build: .
    container_name: crm_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/real_estate_crm?authSource=admin
      DATABASE_NAME: real_estate_crm
      DEBUG: "true"
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - crm_network

volumes:
  mongodb_data:

networks:
  crm_network:
    driver: bridge
