version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crm_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: real_estate_crm
    volumes:
      - mongodb_data:/data/db
    networks:
      - crm_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: crm_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/real_estate_crm?authSource=admin
      DATABASE_NAME: real_estate_crm
      ENVIRONMENT: production
      SECRET_KEY: your-production-secret-key-change-this
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      FB_APP_ID: ""
      FB_APP_SECRET: ""
      FB_PAGE_TOKEN: ""
      FB_PAGE_ID: ""
      GROQ_API_KEY: ""
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: crm_frontend
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
      NODE_ENV: production
      GENERATE_SOURCEMAP: 'false'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - crm_network

volumes:
  mongodb_data:

networks:
  crm_network:
    driver: bridge
