name: Backlog Sync

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run without writing to GitHub'
        required: false
        default: 'false'
  push:
    paths:
      - '.github/backlog.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Sync backlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/sync_backlog.py
